include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # COMMON BEST PRACTICES
    always_declare_return_types: true
    avoid_print: true
    avoid_unnecessary_containers: true
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    prefer_final_fields: true
    prefer_final_locals: true
    use_key_in_widget_constructors: true

    # NAMING & STYLE
    camel_case_types: true
    file_names: true
    constant_identifier_names: false # Useful for constants like MY_CONST
    library_prefixes: true
    avoid_renaming_method_parameters: true
    prefer_single_quotes: true

    # PERFORMANCE & MEMORY
    avoid_redundant_argument_values: true
    avoid_slow_async_io: true
    avoid_multiple_declarations_per_line: true
    prefer_const_declarations: true
    unnecessary_lambdas: true
    unnecessary_null_checks: true
    unnecessary_this: true

    # SAFETY & MAINTAINABILITY
    avoid_types_as_parameter_names: true
    avoid_init_to_null: true
    null_check_on_nullable_type_parameter: true
    use_late_for_private_fields_and_variables: true
    parameter_assignments: false # Allow assigning to parameters
    depend_on_referenced_packages: true

    # FLUTTER SPECIFIC
    avoid_returning_null_for_future: true
    avoid_web_libraries_in_flutter: true
    use_build_context_synchronously: true
    prefer_const_constructors_in_immutables: true
    sort_child_properties_last: true
    avoid_positional_boolean_parameters: true
    always_use_package_imports: true

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.config.dart"
    - "**/*.gen.dart"
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false
