// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQnnqmOtCKDxID-0OGmfT_GTrFDI4guwo',
    appId: '1:705898564069:web:165f89755ac214e722870c',
    messagingSenderId: '705898564069',
    projectId: 'futzone-2b282',
    authDomain: 'futzone-2b282.firebaseapp.com',
    storageBucket: 'futzone-2b282.firebasestorage.app',
    measurementId: 'G-KML7FE5F4M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcHHII31KyQBgb-_4O4uvulkwckWL2_aY',
    appId: '1:705898564069:android:e194a49645e531ea22870c',
    messagingSenderId: '705898564069',
    projectId: 'futzone-2b282',
    storageBucket: 'futzone-2b282.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDa25VSyvra1NYpCK6RNiMhVGYRCymx8po',
    appId: '1:705898564069:ios:3bcda0a2b3f4883e22870c',
    messagingSenderId: '705898564069',
    projectId: 'futzone-2b282',
    storageBucket: 'futzone-2b282.firebasestorage.app',
    iosBundleId: 'com.example.sportAppUser',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDa25VSyvra1NYpCK6RNiMhVGYRCymx8po',
    appId: '1:705898564069:ios:3bcda0a2b3f4883e22870c',
    messagingSenderId: '705898564069',
    projectId: 'futzone-2b282',
    storageBucket: 'futzone-2b282.firebasestorage.app',
    iosBundleId: 'com.example.sportAppUser',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBQnnqmOtCKDxID-0OGmfT_GTrFDI4guwo',
    appId: '1:705898564069:web:cd405899c11c780522870c',
    messagingSenderId: '705898564069',
    projectId: 'futzone-2b282',
    authDomain: 'futzone-2b282.firebaseapp.com',
    storageBucket: 'futzone-2b282.firebasestorage.app',
    measurementId: 'G-MXDL7W32FQ',
  );
}
